name: example
description: "Example for resource_storage_secure"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  resource_storage: ^1.0.0
  resource_storage_secure:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
