name: resource_storage_secure
description: "Secure persistent resource storage implementation based on flutter_secure_storage plugin."
version: 1.0.0
homepage: https://github.com/drstranges/resource_storage_secure
repository: https://github.com/drstranges/resource_storage_secure
issue_tracker: https://github.com/drstranges/resource_storage_secure/issues
topics:
  - storage
  - cache

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter_secure_storage: ">=9.0.0 <10.0.0"
  resource_storage: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0